[package]
name = "solana-mining-pool-program"
description = "Solana Mining Pool program"
documentation = "https://docs.rs/solana-mining-pool-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-vote-program = { workspace = true }
solana-stake-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
solana-logger = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_mining_pool_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
